name: Piu Trading Bot Signal

on:
  schedule:
    # Berjalan setiap 4 jam (00:00, 04:00, 08:00, dst dalam UTC)
    - cron: '0 */4 * * *'
  workflow_dispatch: # Memungkinkan kamu jalankan manual klik tombol

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10' # Gunakan 3.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install "pandas<2.0.0" numpy 
          curl -L https://www.pandas-ta.dev/assets/zip/pandas_ta-0.3.14b0.tar.gz -o pandas-ta.tar.gz
          pip install pandas-ta.tar.gz
          pip install ccxt yfinance requests
          
      - name: Run Bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python bot_final.py
